/**
 * Fetch profile README (project list) + now.md from undivisible/undivisible.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeReadmeBundle, parseReadme } from "../src/parse-readme";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "src", "generated");

const README_URL =
  process.env.PROFILE_README_URL ??
  "https://raw.githubusercontent.com/undivisible/undivisible/main/README.md";
const NOW_URL =
  process.env.NOW_MARKDOWN_URL ??
  "https://raw.githubusercontent.com/undivisible/undivisible/main/now.md";

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, {
    headers: { "user-agent": "undivisible.dev-moonshine-sync" },
  });
  if (!res.ok) throw new Error(`fetch ${url} → ${res.status}`);
  return res.text();
}

mkdirSync(OUT, { recursive: true });

const readmeMd = await fetchText(README_URL);
const nowMd = await fetchText(NOW_URL).catch(() => "");
const bundle = normalizeReadmeBundle(parseReadme(readmeMd));

writeFileSync(
  join(OUT, "readme-projects.ts"),
  `/* generated by scripts/sync-content.ts — do not edit */
import type { ReadmeBundle } from "../parse-readme";

export const readmeProjects: ReadmeBundle = ${JSON.stringify(bundle, null, 2)} as const;
`,
);

writeFileSync(
  join(OUT, "now-markdown.ts"),
  `/* generated by scripts/sync-content.ts — do not edit */
export const nowMarkdown: string = ${JSON.stringify(nowMd)};
`,
);

console.log(
  `synced projects=${bundle.mainProjects.length} utilities=${bundle.utilities.length} now=${nowMd.length}b`,
);
