import { chromium } from "playwright-core";
import { readFileSync, writeFileSync } from "node:fs";

/*
 * Geist Mono → the desktop's fonts, anti-aliased.
 *
 * Two cells: 8x16 for body text, 16x32 for display text. Each glyph is
 * stored as one alpha byte per pixel (coverage 0-255), not 1-bit on/off,
 * so the C side blends it over the background and the edges are smooth
 * instead of jagged. GeistMono-Regular.ttf, SIL OFL 1.1.
 */
const ttfPath = process.argv[2] ?? "/tmp/geist/GeistMono.ttf";
const ttf = readFileSync(ttfPath).toString("base64");

const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage();
await page.setContent("<canvas id=c></canvas>");

async function raster(cw: number, ch: number, size: number, base: number) {
  return page.evaluate(
    async ({ ttf, cw, ch, size, base }) => {
      const face = new FontFace("GM", `url(data:font/ttf;base64,${ttf})`);
      await face.load();
      (document as any).fonts.add(face);
      const c = document.getElementById("c") as HTMLCanvasElement;
      c.width = cw;
      c.height = ch;
      const ctx = c.getContext("2d")!;
      const out: number[][] = [];
      for (let code = 0; code < 256; code++) {
        const g: number[] = new Array(cw * ch).fill(0);
        if (code >= 32 && code < 127) {
          ctx.clearRect(0, 0, cw, ch);
          ctx.font = `${size}px GM`;
          ctx.textBaseline = "alphabetic";
          ctx.fillStyle = "#fff";
          const w = ctx.measureText(String.fromCharCode(code)).width;
          ctx.fillText(String.fromCharCode(code), (cw - w) / 2, base);
          const d = ctx.getImageData(0, 0, cw, ch).data;
          for (let i = 0; i < cw * ch; i++) g[i] = d[i * 4 + 3];
        }
        out.push(g);
      }
      return out;
    },
    { ttf, cw, ch, size, base },
  );
}

function emit(rows: number[][], cw: number, ch: number, name: string) {
  const body = rows
    .map(
      (g, i) =>
        "  " +
        g.map((b) => b.toString()).join(",") +
        `, /* ${i >= 32 && i < 127 ? JSON.stringify(String.fromCharCode(i)) : i} */`,
    )
    .join("\n");
  writeFileSync(
    new URL(`../os-image/de/${name}.h`, import.meta.url).pathname,
    `/*
 * Geist Mono, anti-aliased, ${cw}x${ch} cell. One alpha byte per pixel.
 * Generated by scripts/rasterize-font.ts from GeistMono-Regular.ttf
 * (SIL OFL 1.1). The C side blends this over the background, so text is
 * smooth at every size instead of a doubled bitmap.
 */
#ifndef ALPENGLOWED_${name.toUpperCase()}_H
#define ALPENGLOWED_${name.toUpperCase()}_H

#define ${name.toUpperCase()}_W ${cw}
#define ${name.toUpperCase()}_H ${ch}

static const unsigned char ${name}[256 * ${cw * ch}] = {
${body}
};

#endif
`,
  );
  console.log(`wrote os-image/de/${name}.h (${cw}x${ch})`);
}

emit(await raster(8, 16, 14, 12), 8, 16, "font_small");
emit(await raster(16, 32, 27, 24), 16, 32, "font_large");
await browser.close();
