import { chromium } from "playwright-core";
import { readFileSync, writeFileSync } from "node:fs";

const CW = 16, CH = 32, SIZE = 27, BASE = 24, THRESH = 128;
const ttf = readFileSync("/tmp/geist/GeistMono.ttf").toString("base64");
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage();
await page.setContent(`<canvas id=c width=${CW} height=${CH}></canvas>`);

const rows: number[][] = await page.evaluate(
  async ({ ttf, CW, CH, SIZE, BASE, THRESH }) => {
    const face = new FontFace("GM", `url(data:font/ttf;base64,${ttf})`);
    await face.load();
    (document as any).fonts.add(face);
    const c = document.getElementById("c") as HTMLCanvasElement;
    const ctx = c.getContext("2d")!;
    const out: number[][] = [];
    for (let code = 0; code < 256; code++) {
      const g: number[] = new Array(CH * 2).fill(0);
      if (code >= 32 && code < 127) {
        ctx.clearRect(0, 0, CW, CH);
        ctx.font = `${SIZE}px GM`;
        ctx.textBaseline = "alphabetic";
        ctx.fillStyle = "#fff";
        const w = ctx.measureText(String.fromCharCode(code)).width;
        ctx.fillText(String.fromCharCode(code), (CW - w) / 2, BASE);
        const d = ctx.getImageData(0, 0, CW, CH).data;
        for (let y = 0; y < CH; y++) {
          let hi = 0, lo = 0;
          for (let x = 0; x < CW; x++) {
            if (d[(y * CW + x) * 4 + 3] >= THRESH) {
              if (x < 8) hi |= 0x80 >> x;
              else lo |= 0x80 >> (x - 8);
            }
          }
          g[y * 2] = hi;
          g[y * 2 + 1] = lo;
        }
      }
      out.push(g);
    }
    return out;
  },
  { ttf, CW, CH, SIZE, BASE, THRESH },
);
await browser.close();

const body = rows
  .map((g, i) =>
    "  " + g.map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") +
    `, /* ${i >= 32 && i < 127 ? JSON.stringify(String.fromCharCode(i)) : i} */`,
  )
  .join("\n");
writeFileSync(
  "/Users/undivisible/conductor/workspaces/undivisible.dev-v1/istanbul/web/os-image/de/font16x32.h",
  `/*
 * Geist Mono, rasterized to a 16x32 cell.
 *
 * Generated by scripts/rasterize-font.ts --big from GeistMono-Regular.ttf
 * (SIL Open Font License 1.1). Two bytes per row (16 px, high bit
 * leftmost), 32 rows per glyph. This is the display face: the desktop's
 * large text draws from it at native size instead of doubling the 8x16
 * console font, so headings stop looking like blocks.
 */
#ifndef ALPENGLOWED_FONT16X32_H
#define ALPENGLOWED_FONT16X32_H

static const unsigned char font16x32[256 * 64] = {
${body}
};

#endif
`,
);
for (const ch of "Ag12:") {
  const g = rows[ch.charCodeAt(0)];
  console.log(ch);
  for (let y = 0; y < CH; y++) {
    let line = "";
    for (let x = 0; x < 16; x++) {
      const byte = x < 8 ? g[y * 2] : g[y * 2 + 1];
      const bit = x < 8 ? 0x80 >> x : 0x80 >> (x - 8);
      line += byte & bit ? "#" : ".";
    }
    console.log(line);
  }
}
console.log("wrote os-image/de/font16x32.h");
