import { chromium } from "playwright-core";
import { readFileSync, writeFileSync } from "node:fs";

const ttfPath = process.argv[2] ?? "GeistMono-Regular.ttf";
const size = Number(process.argv[3] ?? 13);
const baseline = Number(process.argv[4] ?? 12);
const thresh = Number(process.argv[5] ?? 110);

const ttf = readFileSync(ttfPath).toString("base64");
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage();
await page.setContent("<canvas id=c width=8 height=16></canvas>");

const rows: number[][] = await page.evaluate(
  async ({ ttf, size, baseline, thresh }) => {
    const face = new FontFace("GM", `url(data:font/ttf;base64,${ttf})`);
    await face.load();
    (document as any).fonts.add(face);
    const c = document.getElementById("c") as HTMLCanvasElement;
    const ctx = c.getContext("2d")!;
    const out: number[][] = [];
    for (let code = 0; code < 256; code++) {
      const glyph: number[] = new Array(16).fill(0);
      if (code >= 32 && code < 127) {
        ctx.clearRect(0, 0, 8, 16);
        ctx.font = `${size}px GM`;
        ctx.textBaseline = "alphabetic";
        ctx.fillStyle = "#fff";
        const w = ctx.measureText(String.fromCharCode(code)).width;
        ctx.fillText(String.fromCharCode(code), (8 - w) / 2, baseline);
        const d = ctx.getImageData(0, 0, 8, 16).data;
        for (let y = 0; y < 16; y++) {
          let bits = 0;
          for (let x = 0; x < 8; x++)
            if (d[(y * 8 + x) * 4 + 3] >= thresh) bits |= 0x80 >> x;
          glyph[y] = bits;
        }
      }
      out.push(glyph);
    }
    return out;
  },
  { ttf, size, baseline, thresh },
);
await browser.close();

const preview = (code: number) =>
  rows[code]
    .map((b) =>
      Array.from({ length: 8 }, (_, i) => (b & (0x80 >> i) ? "#" : ".")).join(""),
    )
    .join("\n");
for (const ch of "AgWmi01?") console.log(ch + "\n" + preview(ch.charCodeAt(0)));

const body = rows
  .map((g, i) =>
    "  " + g.map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") +
    `, /* ${i >= 32 && i < 127 ? JSON.stringify(String.fromCharCode(i)) : i} */`,
  )
  .join("\n");
writeFileSync(
  new URL("../os-image/de/font8x16.h", import.meta.url).pathname,
  `/*
 * Geist Mono, rasterized to the 8x16 console cell.
 *
 * Generated by scripts/rasterize-font.ts from GeistMono-Regular.ttf
 * (SIL Open Font License 1.1). One byte per row, high bit leftmost —
 * the same shape the kernel's own console font has, so nothing that
 * draws text had to change.
 */
#ifndef ALPENGLOWED_FONT8X16_H
#define ALPENGLOWED_FONT8X16_H

static const unsigned char font8x16[256 * 16] = {
${body}
};

#endif
`,
);
console.log("wrote os-image/de/font8x16.h");
