import { parseResumeMarkdown } from "../src/lib/parse-resume-markdown.ts";

const RESUME_PATH = new URL("../../resume.md", import.meta.url);
const OUT_FILE = new URL("../src/data/resume-from-markdown.generated.ts", import.meta.url);

const md = await Bun.file(RESUME_PATH).text();
const doc = parseResumeMarkdown(md);

await Bun.write(
  OUT_FILE,
  `/* generated by scripts/sync-resume.ts — do not edit */\n\nexport const resumeFromMarkdown = ${JSON.stringify(doc, null, 2)};\n`,
);

console.log(`wrote ${OUT_FILE.pathname}`);
console.log(
  `experience: ${doc.experience.length}, project sections: ${doc.projectSections.length}, projects: ${doc.projectSections.reduce((n, s) => n + s.items.length, 0)}`,
);
