/* generated by scripts/sync-resume.ts — do not edit */

export const resumeFromMarkdown = {
  "nameLine": "Max Carter · 祁明思",
  "titleLine": "Software systems builder",
  "siteHref": "https://undivisible.dev/",
  "summary": "I make things for people. Part-time language learner, part-time philosopher, full-time schemer. I build systems, runtimes, interfaces, developer tools, and small pieces of software that feel inevitable. Self-taught full-stack and low-level developer; building production software since age 8.",
  "contact": [
    [
      "Email",
      "max@tsc.hk"
    ],
    [
      "Phone",
      "+61 481 729 894"
    ],
    [
      "Instagram",
      "@undivisible.dev"
    ],
    [
      "Twitter",
      "@makethings4ppl"
    ],
    [
      "GitHub",
      "github.com/undivisible"
    ],
    [
      "Location",
      "Melbourne / Sydney / Hong Kong"
    ]
  ],
  "experience": [
    {
      "role": "Technical Cofounder",
      "org": "The Arkie Company, Graft AI",
      "time": "2026–present",
      "bullets": [
        "Engineering leadership, product direction, and hands-on delivery across web surfaces, automation, and internal systems.",
        "Build custom AI automation systems, product prototypes, client-facing web surfaces, and internal tooling."
      ],
      "subsections": [
        {
          "title": "SaaS products built",
          "items": [
            {
              "name": "Studio of Optimisations",
              "href": "https://optimisations.studio",
              "meta": "Studio of Optimisations · Graft AI · Production · +61 3 8828 9225",
              "desc": "Dual-brand sales funnels (same codebase): Arkie-backed chat, live voice, calendar booking, lead capture, Notion connect portal.",
              "descSegments": [],
              "stack": "SvelteKit 5, TypeScript, Tailwind CSS v4, Cloudflare Workers, Arkie API proxy, Bun."
            },
            {
              "name": "Arkie",
              "href": "https://arkie.company",
              "meta": "",
              "desc": "Arkie · Production · Centralized MCP/AI backend for all Arkie apps: per-app system prompts, tool sets, chat/stream, calendar booking, Stripe/Calendly/Notion webhooks, Gemini Live voice, embeddings, admin console, OAuth for Claude MCP.",
              "descSegments": [
                {
                  "type": "link",
                  "label": "Arkie",
                  "href": "https://arkie.company"
                },
                {
                  "type": "text",
                  "value": " · Production · Centralized MCP/AI backend for all Arkie apps: per-app system prompts, tool sets, chat/stream, calendar booking, Stripe/Calendly/Notion webhooks, Gemini Live voice, embeddings, admin console, OAuth for Claude MCP."
                }
              ],
              "stack": "Rust, Axum, Tokio, Google Gemini, Supabase (PostgREST, Auth, pgvector), Cloudflare Workers/Containers, DigitalOcean SIP edge."
            },
            {
              "name": "Pava",
              "href": "https://pava.studio",
              "meta": "",
              "desc": "Pava · Closed beta (approaching release) · AI content strategist and crossposting: brand chat, idea generation, AI-negotiated Stripe pricing, competitor analysis, video review, enterprise/agency workspaces, 13+ platforms via Late API.",
              "descSegments": [
                {
                  "type": "link",
                  "label": "Pava",
                  "href": "https://pava.studio"
                },
                {
                  "type": "text",
                  "value": " · Closed beta (approaching release) · AI content strategist and crossposting: brand chat, idea generation, AI-negotiated Stripe pricing, competitor analysis, video review, enterprise/agency workspaces, 13+ platforms via Late API."
                }
              ],
              "stack": "Next.js 16, TypeScript, Supabase, Stripe, Google Gemini, Late API, Tailwind CSS v4, Capacitor, Bun."
            },
            {
              "name": "Unthought",
              "href": "https://unthought.arkie.company",
              "meta": "",
              "desc": "Unthought · Alpha · Business platforming: custom domain, AI-generated site, professional email, Cloudflare edge deploy, Stripe checkout, Stalwart mail provisioning, Tangent integration hooks.",
              "descSegments": [
                {
                  "type": "link",
                  "label": "Unthought",
                  "href": "https://unthought.arkie.company"
                },
                {
                  "type": "text",
                  "value": " · Alpha · Business platforming: custom domain, AI-generated site, professional email, Cloudflare edge deploy, Stripe checkout, Stalwart mail provisioning, Tangent integration hooks."
                }
              ],
              "stack": "Next.js 16, TypeScript, Supabase, Cloudflare (OpenNext, D1, R2, Queues), Arkie, Stripe, Porkbun, Bun."
            },
            {
              "name": "Tangent",
              "href": "https://tangent.undivisible.dev",
              "meta": "",
              "desc": "Tangent · Alpha · Discord automation for digital product sellers: Stripe payment webhooks, order fulfillment (keys, roles, content), ticketing, purchase-linked profiles, Gemini RAG support and image verification, event-driven workflows, admin dashboard, MCP tools for store ops.",
              "descSegments": [
                {
                  "type": "link",
                  "label": "Tangent",
                  "href": "https://tangent.undivisible.dev"
                },
                {
                  "type": "text",
                  "value": " · Alpha · Discord automation for digital product sellers: Stripe payment webhooks, order fulfillment (keys, roles, content), ticketing, purchase-linked profiles, Gemini RAG support and image verification, event-driven workflows, admin dashboard, MCP tools for store ops."
                }
              ],
              "stack": "Go (discordgo), SQLite/Postgres, Google Gemini, Astro 4, Alpine.js, htmx, UnoCSS, Cloudflare Workers (MCP, D1, Durable Objects)."
            },
            {
              "name": "Currant",
              "href": "",
              "meta": "",
              "desc": "Currant · Work in progress · Multi-tenant AI sales agents and job management for trades businesses; autonomous agents across WhatsApp, Telegram, SMS, Instagram, Slack, email, and native SIP/RTP phone; leads → quotes → jobs → invoices.",
              "descSegments": [],
              "stack": "Go, Python (FastAPI), Elixir (Phoenix), Rust (telephony), Vlang (filter), SvelteKit, React Native (Expo), Tauri, SurrealDB, Redis, Gemini, Stripe, Square."
            },
            {
              "name": "Waarom",
              "href": "",
              "meta": "",
              "desc": "Waarom · Work in progress · AI step-by-step in-product guidance: GPUI desktop companion, `@waarom/embed` SDK, Crepuscularity static portal and knowledge base.",
              "descSegments": [],
              "stack": "Rust, GPUI, Crepuscularity, Gemini, TypeScript (embed SDK), MV3 web extension runtime."
            }
          ]
        },
        {
          "title": "Client work",
          "items": [
            {
              "name": "AJ Stafford Property Advocates",
              "href": "https://www.ajstafford.com.au",
              "meta": "AJ Stafford Property Advocates",
              "desc": "Chrome MV3 extension for realestate.com.au: finds comparable listings (bedrooms, ±15% price), on-page results widget, tab groups, CSV/TXT export; Buyer Ready Report print mockups and buyer-ready campaign assets.",
              "descSegments": [],
              "stack": "JavaScript, Chrome Extensions MV3, Leaflet, Alpine.js, UnoCSS."
            }
          ]
        }
      ]
    },
    {
      "role": "Founder, Artificer",
      "org": "The Software Company of Hong Kong",
      "time": "2023–present",
      "bullets": [
        "Freelance developer since 2024.",
        "Maintain 32+ public GitHub repositories across systems, runtimes, interfaces, developer tools, AI SDKs, and miniapps.",
        "Primary open-source work includes Crepuscularity, Aurorality, Wax, Equilibrium, and Soliloquy."
      ],
      "subsections": [
        {
          "title": "Platforms being built",
          "items": [
            {
              "name": "Ark",
              "href": "",
              "meta": "Ark",
              "desc": "Ultra-simple hosted app platform (Vercel-style ergonomics, Railway-style flexibility): Rust control-plane API, V language CLI (`deploy`, `logs`, `rollback`), Svelte dashboard, YAML app manifests, open-source `ark-protocol` edge ingress spec.",
              "descSegments": [],
              "stack": "Rust (Axum), V, Svelte 5, SurrealDB, Docker Compose, Bun."
            },
            {
              "name": "Mono",
              "href": "https://github.com/atechnology-company/mono",
              "meta": "Mono",
              "desc": "Post-web computing infrastructure with an open-source `mono-protocol` spec: object-centric, identity-addressed encrypted replication; mesh gossip, gateway relay, using `unthinkclaw` agent runtime, mono-browser shell (Crepuscularity/GPUI).",
              "descSegments": [],
              "stack": "Rust (`mono-protocol`, `mono-mesh`, `mono-gateway`, `mono-agent`, `mono-browser`)."
            }
          ]
        }
      ]
    },
    {
      "role": "Systems and Product Architect",
      "org": "Gizzmo Electronics",
      "time": "late 2024",
      "bullets": [
        "Created websites and companion apps; inspired direction for hardware products across product surfaces, packaging, manuals, and marketing.",
        "Redesigned brand and design in entirety."
      ],
      "subsections": [
        {
          "title": "Client deliverable",
          "items": [
            {
              "name": "Gizzmo Electronics",
              "href": "https://gizzmoelectronics.com",
              "meta": "Gizzmo Electronics",
              "desc": "Product marketing site with Stripe pre-order checkout, brand redesign, and hardware/product narrative across the full customer journey; online product demo and manuals in progress.",
              "descSegments": [],
              "stack": "SvelteKit 5, TypeScript, Vite, Tailwind CSS, Stripe, Netlify."
            },
            {
              "name": "B1",
              "href": "https://gizzmoelectronics.com/b1",
              "meta": "B1",
              "desc": "Boost controller (precision boost control, 2D mapping, real-time display, engine protection); retail box packaging and brand-aligned print artwork for pre-launch SKU, recreated as an online version with instructions.",
              "descSegments": [
                {
                  "type": "text",
                  "value": "Boost controller (precision boost control, 2D mapping, real-time display, engine protection); retail box packaging and brand-aligned print artwork for pre-launch SKU, recreated as an online version with "
                },
                {
                  "type": "link",
                  "label": "instructions",
                  "href": "https://gizzmoelectronics.com/b1/instructions"
                },
                {
                  "type": "text",
                  "value": "."
                }
              ],
              "stack": ""
            },
            {
              "name": "F1",
              "href": "",
              "meta": "F1",
              "desc": "Unreleased product; full retail packaging design to match Gizzmo brand system (not yet public).",
              "descSegments": [],
              "stack": ""
            }
          ]
        }
      ]
    }
  ],
  "projectSections": [],
  "skills": [
    [
      "Languages",
      "Rust, Swift, TypeScript/JavaScript, Python, Go, V, Zig, C / C#"
    ],
    [
      "Frontend",
      "React, Next.js, SvelteKit, Solid, Tailwind, Astro, WebGL, SwiftUI, Crepuscularity"
    ],
    [
      "Systems",
      "GPUI, Ratatui, MV3 extensions, FFI, UniFFI, Servo, V8, WASM, Linux"
    ],
    [
      "AI / Data",
      "OpenAI, MCP, RAG, Transformers.js, local models, Hugging Face, Supabase, PostgreSQL, SurrealDB"
    ],
    [
      "Infra",
      "Cloudflare Workers, Docker, GitHub Actions, CI/CD, SQLite"
    ]
  ],
  "education": [
    "Certificate III in Information Technology coursework, Box Hill Institute. Completing unfinished units this year.",
    "VCE coursework at Eltham High School, including Information Technology, Applied Computing, Politics, Philosophy, Extended Investigation, Linguistics, and Indonesian; left before Year 12 completion to build full time."
  ],
  "humanLanguages": [
    "Cantonese",
    "English",
    "Russian",
    "Mandarin",
    "Indonesian",
    "Learning Japanese"
  ],
  "community": [
    "Volunteer English teacher for Russian speakers online, 2022–present.",
    "Barbie CTF 2023, Petrozavodsk: 12th place in Russian exploit competition.",
    "PECAN CTF 2025: 15th nationally, 4th in division."
  ],
  "interests": [
    "Learning",
    "Travel",
    "Cooking",
    "Photography",
    "Phenomenology",
    "Existentialism",
    "Language learning",
    "Science-based lifting",
    "UFC & Wrestling"
  ]
};
