/* generated by scripts/sync-resume.ts — do not edit */

export const resumeFromMarkdown = {
  "nameLine": "Max Carter · 祁明思",
  "titleLine": "Software systems builder",
  "siteHref": "https://undivisible.dev/",
  "summary": "I make things for people. Part-time language learner, part-time philosopher, full-time schemer. I build systems, runtimes, interfaces, developer tools, and small pieces of software that feel inevitable. Self-taught full-stack and low-level developer; building production software since age 8.",
  "contact": [
    [
      "Email",
      "max@undivisible.dev"
    ],
    [
      "Phone",
      "+61 481 729 894"
    ],
    [
      "Instagram",
      "@undivisible.dev"
    ],
    [
      "Twitter",
      "@makethings4ppl"
    ],
    [
      "GitHub",
      "github.com/undivisible"
    ],
    [
      "Location",
      "Melbourne / Sydney / Hong Kong"
    ]
  ],
  "experience": [
    {
      "role": "Technical Cofounder",
      "org": "The Arkie Company",
      "time": "2024–present",
      "bullets": [
        "Engineering leadership, product direction, and hands-on delivery across web surfaces, automation, and internal systems.",
        "Build custom AI automation systems, product prototypes, client-facing web surfaces, and internal tooling."
      ],
      "subsections": [
        {
          "title": "SaaS products built",
          "items": [
            {
              "name": "Studio of Optimisations",
              "href": "https://optimisations.studio",
              "meta": "Studio of Optimisations · Graft AI · Production · +61 3 8828 9225",
              "desc": "Dual-brand sales funnels (same codebase): Arkie-backed chat, live voice, calendar booking, lead capture, Notion connect portal.",
              "stack": "SvelteKit 5, TypeScript, Tailwind CSS v4, Cloudflare Workers, Arkie API proxy, Bun."
            },
            {
              "name": "Arkie",
              "href": "https://arkie.company",
              "meta": "",
              "desc": "Arkie · Production · Centralized MCP/AI backend for all Arkie apps: per-app system prompts, tool sets, chat/stream, calendar booking, Stripe/Calendly/Notion webhooks, Gemini Live voice, embeddings, admin console, OAuth for Claude MCP.",
              "stack": "Rust, Axum, Tokio, Google Gemini, Supabase (PostgREST, Auth, pgvector), Cloudflare Workers/Containers, DigitalOcean SIP edge."
            },
            {
              "name": "Pava",
              "href": "https://pava.studio",
              "meta": "",
              "desc": "Pava · Closed beta (approaching release) · AI content strategist and crossposting: brand chat, idea generation, AI-negotiated Stripe pricing, competitor analysis, video review, enterprise/agency workspaces, 13+ platforms via Late API.",
              "stack": "Next.js 16, TypeScript, Supabase, Stripe, Google Gemini, Late API, Tailwind CSS v4, Capacitor, Bun."
            },
            {
              "name": "Unthought",
              "href": "https://unthought.arkie.company",
              "meta": "",
              "desc": "Unthought · Alphas · Business platforming: custom domain, AI-generated site, professional email, Cloudflare edge deploy, Stripe checkout, Stalwart mail provisioning, Tangent integration hooks.",
              "stack": "Next.js 16, TypeScript, Supabase, Cloudflare (OpenNext, D1, R2, Queues), Arkie, Stripe, Porkbun, Bun."
            },
            {
              "name": "Tangent",
              "href": "https://tangent.undivisible.dev",
              "meta": "",
              "desc": "Tangent · Alpha · Discord automation for digital product sellers: Stripe payment webhooks, order fulfillment (keys, roles, content), ticketing, purchase-linked profiles, Gemini RAG support and image verification, event-driven workflows, admin dashboard, MCP tools for store ops.",
              "stack": "Go (discordgo), SQLite/Postgres, Google Gemini, Astro 4, Alpine.js, htmx, UnoCSS, Cloudflare Workers (MCP, D1, Durable Objects)."
            },
            {
              "name": "Currant",
              "href": "",
              "meta": "",
              "desc": "Currant · Work in progress · Multi-tenant AI sales agents and job management for trades businesses; autonomous agents across WhatsApp, Telegram, SMS, Instagram, Slack, email, and native SIP/RTP phone; leads → quotes → jobs → invoices.",
              "stack": "Go, Python (FastAPI), Elixir (Phoenix), Rust (telephony), Vlang (filter), SvelteKit, React Native (Expo), Tauri, SurrealDB, Redis, Gemini, Stripe, Square."
            },
            {
              "name": "Waarom",
              "href": "",
              "meta": "",
              "desc": "Waarom · Work in progress · AI step-by-step in-product guidance: GPUI desktop companion, `@waarom/embed` SDK, Crepuscularity static portal and knowledge base.",
              "stack": "Rust, GPUI, Crepuscularity, Gemini, TypeScript (embed SDK), MV3 web extension runtime."
            }
          ]
        },
        {
          "title": "Client work",
          "items": [
            {
              "name": "AJ Stafford Property Advocates",
              "href": "https://www.ajstafford.com.au",
              "meta": "AJ Stafford Property Advocates",
              "desc": "Chrome MV3 extension for realestate.com.au: finds comparable listings (bedrooms, ±15% price), on-page results widget, tab groups, CSV/TXT export; Buyer Ready Report print mockups and buyer-ready campaign assets.",
              "stack": "JavaScript, Chrome Extensions MV3, Leaflet, Alpine.js, UnoCSS."
            }
          ]
        }
      ]
    },
    {
      "role": "Founder, Artificer",
      "org": "The Software Company of Hong Kong, atechnology company",
      "time": "2023–present",
      "bullets": [
        "Freelance developer since 2024.",
        "Maintain 32+ public GitHub repositories across systems, runtimes, interfaces, developer tools, AI SDKs, and miniapps.",
        "Primary open-source work includes Crepuscularity, Aurorality, Wax, Equilibrium, and Soliloquy."
      ],
      "subsections": [
        {
          "title": "Platforms built",
          "items": [
            {
              "name": "Ark",
              "href": "",
              "meta": "Ark",
              "desc": "Ultra-simple hosted app platform (Vercel-style ergonomics, Railway-style flexibility): Rust control-plane API, V language CLI (`deploy`, `logs`, `rollback`), Svelte dashboard, YAML app manifests, `ark-protocol` edge ingress.",
              "stack": "Rust (Axum), V, Svelte 5, SurrealDB, Docker Compose, Bun."
            },
            {
              "name": "Mono",
              "href": "https://github.com/atechnology-company/mono",
              "meta": "Mono",
              "desc": "Post-web computing infrastructure: object-centric, identity-addressed encrypted replication; mesh gossip, gateway relay, using `unthinkclaw` agent runtime, mono-browser shell (Crepuscularity/GPUI).",
              "stack": "Rust (`mono-protocol`, `mono-mesh`, `mono-gateway`, `mono-agent`, `mono-browser`)."
            }
          ]
        }
      ]
    },
    {
      "role": "Systems and Product Architect",
      "org": "Gizzmo Electronics",
      "time": "late 2024",
      "bullets": [
        "Created websites and companion apps; inspired direction for hardware products across product surfaces, packaging, manuals, and marketing.",
        "Redesigned brand and design in entirety."
      ],
      "subsections": [
        {
          "title": "Client deliverable",
          "items": [
            {
              "name": "Gizzmo Electronics",
              "href": "https://gizzmoelectronics.com",
              "meta": "Gizzmo Electronics",
              "desc": "Product marketing site with Stripe pre-order checkout, brand redesign, and hardware/product narrative across the full customer journey; online product demo and manuals in progress.",
              "stack": "SvelteKit 5, TypeScript, Vite, Tailwind CSS, Stripe, Netlify."
            },
            {
              "name": "B1",
              "href": "",
              "meta": "B1",
              "desc": "Boost controller (precision boost control, 2D mapping, real-time display, engine protection); retail box packaging and brand-aligned print artwork for pre-launch SKU.",
              "stack": ""
            },
            {
              "name": "F1",
              "href": "",
              "meta": "F1",
              "desc": "Unreleased product; full retail packaging design to match Gizzmo brand system (not yet public).",
              "stack": ""
            }
          ]
        }
      ]
    }
  ],
  "projectSections": [
    {
      "title": "Platforms & frameworks",
      "intro": "Crepuscularity · GitHub — Aurorality — Subprojects",
      "items": [
        {
          "name": "Inauguration (WIP)",
          "href": "https://github.com/tschk/inauguration",
          "meta": "Inauguration (WIP)",
          "desc": "Experimental multi-frontend compiler/runtime targeting Core IR, SIL analysis, hot reload, and ultrafast incremental workflows.",
          "stack": "Rust."
        },
        {
          "name": "Equilibrium",
          "href": "https://github.com/tschk/equilibrium",
          "meta": "Equilibrium",
          "desc": "Load C-compatible code into Rust with one call; auto-detects sources, compiles, exposes as Rust modules.",
          "stack": "Rust, C FFI."
        },
        {
          "name": "Eqswift",
          "href": "https://github.com/tschk/eqswift",
          "meta": "Eqswift",
          "desc": "Rust → Swift FFI with minimal boilerplate (companion to Equilibrium).",
          "stack": "Rust, Swift."
        },
        {
          "name": "Wax",
          "href": "https://github.com/tschk/wax",
          "meta": "Wax",
          "desc": "Fast Homebrew-compatible package manager; formulae, bottles, casks, lockfiles, async parallel installs; experimental WinGet/Scoop/Nix-like support.",
          "stack": "Rust."
        }
      ]
    },
    {
      "title": "Operating systems & runtimes",
      "intro": "Soliloquy — RV8 — Other",
      "items": [
        {
          "name": "Experiences",
          "href": "",
          "meta": "Experiences",
          "desc": "Spatial web exploration on Unity WASM.",
          "stack": "Unity, WebAssembly, TypeScript, Kotlin, Swift and Rust."
        },
        {
          "name": "Atmosphere",
          "href": "",
          "meta": "Atmosphere",
          "desc": "Native sync and ecosystem layer for every device; local-first and homelab support.",
          "stack": "Rust (in development; no public repo yet)."
        }
      ]
    },
    {
      "title": "macOS tooling · [semitechnological](https://github.com/semitechnological)",
      "intro": "",
      "items": [
        {
          "name": "Tile (WIP)",
          "href": "https://github.com/semitechnological/tile",
          "meta": "Tile (WIP)",
          "desc": "Mosaic-style tiling window manager, canvas, and multiplexer for macOS.",
          "stack": "Rust, macOS APIs."
        },
        {
          "name": "Otto (WIP)",
          "href": "",
          "meta": "Otto (WIP)",
          "desc": "AI-powered ottocomplete anywhere on your Mac. Built with SwiftUI and Rust + Eqswift.",
          "stack": ""
        },
        {
          "name": "Rover (WIP)",
          "href": "",
          "meta": "Rover (WIP)",
          "desc": "Utilities and plugin system for Mac, inspired by Raycast + Ghostty. Built with Crepuscularity, SwiftUI and Rust.",
          "stack": ""
        }
      ]
    },
    {
      "title": "Websites",
      "intro": "",
      "items": [
        {
          "name": "Standpoint",
          "href": "https://standpoint.undivisible.dev",
          "meta": "Standpoint · GitHub",
          "desc": "Opinion platform for tier lists, polls, and Spectrum (party game on a prompt-based spectrum).",
          "stack": "SvelteKit, TypeScript, Tailwind CSS, Cloudflare Workers/Durable Objects, Vite, Bun."
        },
        {
          "name": "Unthinkmail",
          "href": "https://unthinkmail.undivisible.dev",
          "meta": "Unthinkmail · GitHub",
          "desc": "MCP server for IMAP-supported email.",
          "stack": "Cloudflare Workers, Hono, Wrangler, MCP, Bun."
        },
        {
          "name": "Notes",
          "href": "https://notes.undivisible.dev",
          "meta": "Notes · GitHub",
          "desc": "Minimal note taker with Google Fonts, code highlighting, and Notion-style markdown editing.",
          "stack": "Svelte 5, Vite, Tailwind CSS, CodeMirror, Bun."
        },
        {
          "name": "Bublik",
          "href": "https://bublik.undivisible.dev",
          "meta": "Bublik · GitHub",
          "desc": "Canvas tool for custom frequency soundscapes.",
          "stack": "Rust, Leptos (CSR/WASM), Web Audio API."
        },
        {
          "name": "Alphabets",
          "href": "https://alphabets.undivisible.dev",
          "meta": "Alphabets · GitHub",
          "desc": "Learn any Unicode-supported alphabet via cards, quizzes, and completion tables.",
          "stack": "React, TypeScript, Vite, Tailwind CSS, Capacitor (iOS/Android), Bun."
        },
        {
          "name": "Infrastruct",
          "href": "https://infrastruct.undivisible.dev",
          "meta": "Infrastruct · GitHub",
          "desc": "Belief-agnostic jurisprudence local AI search (SearXNG, DuckDuckGo, Transformers.js, Browser Prompt API).",
          "stack": "Next.js 15, React 19, TypeScript, Tailwind CSS, Transformers.js, Bun."
        },
        {
          "name": "AKH (archived)",
          "href": "https://akh.undivisible.dev",
          "meta": "AKH (archived) · GitHub",
          "desc": "Islamic uniplatform (archived).",
          "stack": "Svelte, TypeScript."
        }
      ]
    },
    {
      "title": "Programs",
      "intro": "",
      "items": [
        {
          "name": "Drift",
          "href": "https://github.com/undivisible/drift-wallpaper",
          "meta": "Drift",
          "desc": "macOS Drift screensaver as live wallpaper on Linux, macOS, and Windows; Spotify and Apple Music now playing.",
          "stack": "Rust."
        },
        {
          "name": "Vro",
          "href": "https://github.com/undivisible/vro",
          "meta": "Vro",
          "desc": "Ultraminimal micro-inspired text editor.",
          "stack": "V."
        },
        {
          "name": "Unthinkclaw",
          "href": "https://github.com/undivisible/unthinkclaw",
          "meta": "Unthinkclaw",
          "desc": "OpenClaw-scale local agent runtime at a fraction of the size; agent swarms, multi-channel messaging.",
          "stack": "Rust."
        },
        {
          "name": "Poke Around",
          "href": "https://github.com/undivisible/poke-around",
          "meta": "Poke Around",
          "desc": "Lets Poke interact with your computer on major OSes.",
          "stack": "Zig and Typescript."
        },
        {
          "name": "Unelaborate",
          "href": "https://github.com/undivisible/unelaborate",
          "meta": "Unelaborate",
          "desc": "Minecraft client in native SwiftUI with Modrinth modpack, shader, and resource-pack loading.",
          "stack": "Swift, SwiftUI."
        },
        {
          "name": "YCYEStim",
          "href": "https://github.com/undivisible/ycyestim",
          "meta": "YCYEStim",
          "desc": "iOS controller for YCY-YOKONEX Gen 1 and 2 electrostimulation hardware over Bluetooth LE (optional user-owned HTTP/WebSocket bridge); dual-channel waveforms, presets and programs, safety limits, HealthKit and watchOS heart-rate adaptive output.",
          "stack": "Swift 6, SwiftUI, CoreBluetooth, HealthKit, watchOS."
        },
        {
          "name": "Bluetooth Terminal",
          "href": "https://github.com/undivisible/bluetooth-terminal",
          "meta": "Bluetooth Terminal",
          "desc": "macOS Bluetooth LE terminal for scanning, connecting, and exchanging raw payloads with nearby devices.",
          "stack": "Swift, SwiftUI, CoreBluetooth."
        },
        {
          "name": "Anywhere",
          "href": "https://github.com/undivisible/anywhere",
          "meta": "Anywhere",
          "desc": "Browser extension that turns AI chat responses into interactive UIs (widgets, panels, forms, charts) via custom response tags.",
          "stack": "Rust, Crepuscularity WebExt, MV3."
        }
      ]
    },
    {
      "title": "Libraries & infrastructure",
      "intro": "",
      "items": [
        {
          "name": "rs_ai",
          "href": "https://github.com/undivisible/rs_ai",
          "meta": "rs_ai",
          "desc": "Async-first Rust AI SDK for cloud and on-device providers (`rs_ai_local`: Gemini Nano, Foundation Models, Phi Silica, Browser Prompt API).",
          "stack": "Rust."
        },
        {
          "name": "rs_imessage",
          "href": "https://github.com/undivisible/rs_imessage",
          "meta": "rs_imessage",
          "desc": "Rust iMessage library and CLI for macOS.",
          "stack": "Rust."
        },
        {
          "name": "rs_facetime",
          "href": "https://github.com/undivisible/rs_facetime",
          "meta": "rs_facetime",
          "desc": "Rust FaceTime library and CLI for macOS.",
          "stack": "Rust."
        },
        {
          "name": "Stalwart Lite",
          "href": "https://github.com/arkiecompany/stalwart-lite",
          "meta": "Stalwart Lite",
          "desc": "Stalwart mail server as an in-process Rust crate; IMAP, SMTP, management API; embedding and local-first.",
          "stack": "Rust."
        },
        {
          "name": "crosspost-rs",
          "href": "https://github.com/arkiecompany/crosspost-rs",
          "meta": "crosspost-rs",
          "desc": "Crossposting library for multiple social platforms.",
          "stack": "Rust."
        },
        {
          "name": "ark-protocol",
          "href": "https://github.com/arkiecompany/ark-protocol",
          "meta": "ark-protocol",
          "desc": "Open protocol and reference implementation for exposing many local VPS services behind one HTTPS/WebSocket ingress; manifest routing, adapter APIs, Cloudflare-compatible edge multiplexing.",
          "stack": "JavaScript/TypeScript, Cloudflare."
        },
        {
          "name": "monoprotocol",
          "href": "https://github.com/atechnology-company/monoprotocol",
          "meta": "monoprotocol",
          "desc": "Normative draft sync protocol: wire format, crypto (HKDF, AES-256-GCM), replicated object model, journals, capabilities; Rust reference crate on crates.io with golden conformance vectors (JSON/CBOR).",
          "stack": "Rust, Markdown spec, conformance fixtures."
        }
      ]
    }
  ],
  "skills": [
    [
      "Languages",
      "Rust, Swift, TypeScript/JavaScript, Python, Go, V, Zig, C / C#"
    ],
    [
      "Frontend",
      "React, Next.js, SvelteKit, Solid, Tailwind, Leptos, Imba, Astro WebGL, SwiftUI, Crepuscularity"
    ],
    [
      "Systems",
      "GPUI, Ratatui, MV3 extensions, FFI, UniFFI, Servo, V8, WASM, Linux"
    ],
    [
      "AI / Data",
      "OpenAI, MCP, RAG, Transformers.js, local models, Hugging Face, Supabase, PostgreSQL, SurrealDB"
    ],
    [
      "Infra",
      "Cloudflare Workers, Docker, GitHub Actions, CI/CD, SQLite"
    ]
  ],
  "education": [
    "Certificate III in Information Technology coursework, Box Hill Institute. Completing unfinished units this year.",
    "VCE coursework at Eltham High School, including Information Technology, Applied Computing, Politics, Philosophy, Extended Investigation, Linguistics, and Indonesian; left before Year 12 completion to build full time."
  ],
  "humanLanguages": [
    "Cantonese",
    "English",
    "Russian",
    "Mandarin",
    "Indonesian",
    "Learning Japanese and German"
  ],
  "community": [
    "Volunteer English teacher for Russian speakers online, 2022–present.",
    "Barbie CTF 2023, Petrozavodsk: 12th place in Russian exploit competition.",
    "PECAN CTF 2025: 15th nationally, 4th in division."
  ],
  "interests": [
    "Learning",
    "Travel",
    "Cooking",
    "Photography",
    "Phenomenology",
    "Existentialism",
    "Consciousness hacking",
    "Language learning",
    "Computer systems",
    "Science-based lifting",
    "UFC & Wrestling"
  ]
};
