#!/bin/sh
# temple
# 640x480 16 colours was a covenant
T=/dev/tty1
printf '\033]P0000080' > "$T"
printf '\033]P7ffff55' > "$T"
clear
printf '\n\n  An idiot admires complexity, a genius admires simplicity.\n'
printf '\n  terrence andrew davis, 1969-2018.\n  templeos: kernel, compiler, language. alone.\n'
printf '\n  \033[90m[enter restores the sky]\033[0m '
read -r _
alpensky
